# Generated by Django 4.0 on 2023-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Crop', models.IntegerField()),
                ('Acres', models.IntegerField()),
                ('Measured', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('tavg', models.FloatField()),
                ('tmin', models.FloatField()),
                ('tmax', models.FloatField()),
            ],
        ),
    ]
